### ISSUE TITLE
Didn't you mean bytes?

### ISSUE THREAD

**Issue by montoyo** [paultech/TC-Specs#2]
Hello!
Nice work; I love it ;) !
Correct me if I'm wrong, but isn't "octet" a French word? Didn't you mean "byte"?

**Comment by Zardoz89** [comment]
- "A set of bits constituting the smallest unit of addressable memory in a given computer, typically eight bits."
- "An octet is a unit of digital information in computing and telecommunications that consists of eight bits. "

Usually a byte is a octet. However, not all computer uses a byte of 8 bits. In this case, the DCPU-16 smallest unit of addressable memory are 16 byte values. So to avoid confusion, here is use "octet" to avoid confusion.

**Comment by montoyo** [comment]
Oh, okay, good to know. Never saw this word in english, so...
Sorry!

**Comment by paultech** [comment]
No problem! Feel free to let us know of any other questions!
